### Get All Perusahaan (Admin Only)
GET http://localhost:5000/admin/perusahaan
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NTllNTcwYWRiZjdiZTlhZTAzYTk2OCIsIm5hbWUiOiJCdWRpIFNhbnRvc28gVXBkYXRlZCIsImVtYWlsIjoiYnVkaS51cGRhdGVkQGV4YW1wbGUuY29tIiwicm9sZSI6ImFsdW1uaSIsImlhdCI6MTc1MDc4OTM4OCwiZXhwIjoxNzUwODc1Nzg4fQ.L2Oe_waRNwNOA7zApEDWQBEj7gI5aGdLjiH5fY-YYwGda4_I-Ln9hSIVr13206di-Q9ioMsstRF_WFMo-SGjLM8orKJ3uBUzTcEUeneEhryFlw3pNL4trFuNM7Cc6gPc9lJkfiZ6HK95PaQJ9iQYF4zeIPI_vd407k91Cz7TcN1Zh6LL4pvH4Ts4kMDkUFsLvd1eCeH6vICAfpOpDrYK1kqEijWl-tpP_eHzBHZN7T1bjla487fncBvHNdC1F2SbtgWODhncIe194hCg8w3wvxGkUxsrWwBMr7CdXWnv74KirFBWEIaXskiGWMK_eZIiDQxgAPUDphXiDTiThhhEWw

### Get All Alumni (Admin Only)
GET http://localhost:5000/admin/alumni
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NTllNTcwYWRiZjdiZTlhZTAzYTk2OCIsIm5hbWUiOiJCdWRpIFNhbnRvc28gVXBkYXRlZCIsImVtYWlsIjoiYnVkaS51cGRhdGVkQGV4YW1wbGUuY29tIiwicm9sZSI6ImFsdW1uaSIsImlhdCI6MTc1MDc4OTM4OCwiZXhwIjoxNzUwODc1Nzg4fQ.L2Oe_waRNwNOA7zApEDWQBEj7gI5aGdLjiH5fY-YYwGda4_I-Ln9hSIVr13206di-Q9ioMsstRF_WFMo-SGjLM8orKJ3uBUzTcEUeneEhryFlw3pNL4trFuNM7Cc6gPc9lJkfiZ6HK95PaQJ9iQYF4zeIPI_vd407k91Cz7TcN1Zh6LL4pvH4Ts4kMDkUFsLvd1eCeH6vICAfpOpDrYK1kqEijWl-tpP_eHzBHZN7T1bjla487fncBvHNdC1F2SbtgWODhncIe194hCg8w3wvxGkUxsrWwBMr7CdXWnv74KirFBWEIaXskiGWMK_eZIiDQxgAPUDphXiDTiThhhEWw

### Get Admin Profile (/me) (Admin Only)
GET http://localhost:5000/admin/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NWMyYTRhNzM5MzMxODhiMGM3MmQyMSIsInVzZXJuYW1lIjoiYWRtaW4xIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUxMzY2MTcyLCJleHAiOjE3NTEzNjc5NzJ9.ESz1H8q70IFy5lLyO6M_BlH38AotDjEzgVWqQhKkTFRPwvNO3SHCzQSbF-8nmnyW3ne2XxDGmv2x21q7yqLm2YkvcD4rg2UqkDrqRAJDBkeLiFpihk_Fon77RTudMHVJqdLIjxw4r12xCd4l3HuPRp-fRN3SMXubca9BRXOYG_nu9cm-JQAL9Fd3Hi29vXfPHN77A6-zAC0ij3ikNOMDb7s6l8_u0GQ8HZRIin43yMovMux3_SMuJn4XPK03gdIj2Ft5KJcdN1kwB1WgyaIxn-azLs25R2y3c0jcpppGubYjhtn05k-t0DKbk9qHIsLxx5LCISstj7_zdq0fC9vEMg


### Delete Alumni by ID (Admin Only)
DELETE http://localhost:5000/admin/alumni/685c266d3c044b2bf8775cae
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NWMyYTRhNzM5MzMxODhiMGM3MmQyMSIsInVzZXJuYW1lIjoiYWRtaW4xIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUzNDQ5ODIzLCJleHAiOjE3NTM0NTE2MjN9.B2u2gFMhH4yec2GSDeu6bzmrlQtwRpsqsb_1RdZtOyN_PGE2ytk8VZS5YrasGX8LCJ8RjeQ9oKvueC7eCAEgZJhdv0-ONA7tjCCS55WMUowKKcmnTolZ1Vb1wfRAT1VHXRArHw4NIx6KUlnPkIhyYrOtY2UpigERkjlYI0yt8Hju9WX9z-Hb3Qey3n1dNEaeE5gE06uakeuPiBsd133RkLJYG-Vzg9PlqQOa_c98Awj9rgtCbwdi9Jq2ZIm_JAcGG-dfQ8NaOllAonzZwHYv7pSzNBs9_hSApK9cenXFH-aaMWa2bazKYR9v33dRvsQ7jThK8I3DF2Uc3XheBoV4_A
