### Upload CV (PDF) oleh alumni
POST ttps://tugasakhir-production-6c6c.up.railway.app/cv/upload
Authorization: Bearer <ISI_TOKEN_JWT_ANDA>
Content-Type: multipart/form-data

cv=@/path/to/your/cv.pdf


### Ambil CV milik alumni yang sedang login
GET ttps://tugasakhir-production-6c6c.up.railway.app/cv/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ODhlNzczMzJmNmVlNmEyZTMwN2QwNSIsIm5hbWUiOiJuYW5kYSBuYWRsaXJpbiAyIiwiZW1haWwiOiJhbHVtbmkudXBkYXRlZEBleGFtcGxlLmNvbSIsInJvbGUiOiJhbHVtbmkiLCJpYXQiOjE3NTQ3ODU5MzksImV4cCI6MTc1NDc4NzczOX0.TWCFIMAesU6nIEpCa3Fix0cPbbQixRd1KWAERAoOuL-1iCTg_hIC4obRhfmasCx4vfabLzSK3Hae-r1ZsTgAkRx4iv5FIvmYMGWAYOf-QKtoncJ3XXkJaWg1UvP9JExjc6WZhGqGmrE2t7zDZwoi_521yEb6sz33HA5BcQNr82JSSpJok6MCDoZXe-ITiSDY-sPr6-DJNQ-S6x3udL48y9MO6VVqWqI2fcD9ijyAfcnMqeQpkOpLasVhciN_PDzX3t2NzE-O_y9HMg3Yi3n44YdkW1ZraHMBdiH75ed2vhEsZTIythHjwvkD3uQPynLYXdMrTnnxUWy1NC2wJompxw
### Hapus CV milik alumni yang sedang login
DELETE ttps://tugasakhir-production-6c6c.up.railway.app/cv/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ODU2YWQzYzYyNDNhOGJhZTVkMzNmZCIsIm5hbWFfcGVydXNhaGFhbiI6IlBUIE1hanUgSmF5YSAyIiwiZW1haWxfcGVydXNhaGFhbiI6ImhyZEBtYWp1amF5YXVwZGF0ZS5jb20iLCJyb2xlIjoicGVydXNhaGFhbiIsImlhdCI6MTc1NDc4NjAzNiwiZXhwIjoxNzU0Nzg3ODM2fQ.sW3pJqAnbRu4d8ar_Fs5UKi5Kx2Z0y-5iRPcOToSKc6gyla6j_5bxtrymm6IysEvKZ73lLRZVNAlb6drH1z-ktii89xNUr_J9e9ey0rJ18MLaUEMQS6eNHd2oG3naYqZiFE4nGYUuSaWti8VSEfqgYIDBs6dwozfJp1BX4hFWdsGDXJ-bR848ottWvKJogwDLSZBsKzuF2f33EsCueezgEFVg0fXeedNrXA_SQKBMgBpUTPgBOkQhvKYXh3rjZql74mTQNqIasaO4lHUq1wIfJxYfJO5n3Q_CXFFB3uWKn6sO_e7Se7zNT4cIyF5HGm_yRK08E9ik2q-9WblqungQg

### Ambil CV milik alumni tertentu (untuk perusahaan)
GET ttps://tugasakhir-production-6c6c.up.railway.app/cv/?alumniId=6888e77332f6ee6a2e307d05
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ODU2YWQzYzYyNDNhOGJhZTVkMzNmZCIsIm5hbWFfcGVydXNhaGFhbiI6IlBUIE1hanUgSmF5YSAyIiwiZW1haWxfcGVydXNhaGFhbiI6ImhyZEBtYWp1amF5YXVwZGF0ZS5jb20iLCJyb2xlIjoicGVydXNhaGFhbiIsImlhdCI6MTc1NDc4NjE5OSwiZXhwIjoxNzU0Nzg3OTk5fQ.lJWFCbl6s3AWkGGCvDAvTqQ0xk-gcRwF3_jmNe7wTRW8PmrtTppacB8cNMu5T58Gw918AlBclAJjhlgl5DbonsjVDXXasU3djI8MQ4niIQc1-xYappOg5nKaKJcYTTww2QD9TwG0uYg7kgpONorMLep-B2NJBdqGtd2P9wJrF869368TAF3tug_m1miTZQEiATDjm3K6YHZ0MdHJUYuZDO6abwHlE7hmFkjgNKDtLRaey_PnBJbjFpUaiZ3UaFUx8ynZD7n3P1VAp6TcW88zKKq3QJpSqrPNt0zp9WBVjt-qf4e4Nb9swr1q7LUnLLGvfuPocd3qhjv8bDL_Q7H7Hw