### Delete Perusahaan by Admin
DELETE http://localhost:5000/admin/perusahaan/6883a57a7a3bc6197de54843
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NWMyYTRhNzM5MzMxODhiMGM3MmQyMSIsInVzZXJuYW1lIjoiYWRtaW4xIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUzNDU3NzY2LCJleHAiOjE3NTM0NTk1NjZ9.NSQnOp-FU_U4R1hD7SbLHZrEZXsle6LGtGisTcTlyyxgvVHERo8XtxpFliWAVRIHbjLZuTNG3fUDMQLUw4AJRxnEKckHPNIP3GKR2xoUYENxXhkyABr1kF6fW_7Ncsh-uk9qphJTXlEyPEEWCGSwVDp9qC4uHEShLWc6mp7AJYBtbXh0s_XaPwnPjDUzl0aL5NMdt_8csTq1o0WrX-WhPF0-Y1xrUUNrc-D6f76Tw741kAH13CnHG3hjpq1X3Ka2-_Oj38ql-RYOPKQmuAQCEKqf0izjXMMwRJWLW44Z_dZXir1Wign_AGeg2suy95QP91h7-_QQzLg2jsbuItfTzQ
