### Create Forum Post
POST https://tugasakhir-production-6c6c.up.railway.app/forum/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ODU2YWQzYzYyNDNhOGJhZTVkMzNmZCIsIm5hbWFfcGVydXNhaGFhbiI6IlBUIE1hanUgSmF5YSAyIiwiZW1haWxfcGVydXNhaGFhbiI6ImhyZEBtYWp1amF5YXVwZGF0ZS5jb20iLCJyb2xlIjoicGVydXNhaGFhbiIsImlhdCI6MTc1NDc2NzU2MSwiZXhwIjoxNzU0NzY5MzYxfQ.E-lIPDb8Ecuzm2fvm5089O1SgehzVN_DwR6nZ5uB8_ew_uG_zm7MU_lk7L4VqqYcCRw5a7qPma3E2s0yfz0cx4PwLd6AdSBcrkuPqH6sbz8GFjD_rKMv3eXezHPrXIUUyoR5NCd7jL3aT4reKSylvFkjREejnF0_CPjUWkFP9C6f-8_M-toF3mI_jdKOsuKxERxUtMQeZkyPQxx3iJUcviLB7hR5EBksALtIXILaiu_dpcjJAGYUygRfVCWvKwhDNEtisonJLKXnti8dsWH7iBajRs6gOEOiJ6Z9gypVgsFLBC3HWqJ4nKVhxVN5VXkK9dMTrDcaV9UADTf-GWYAPQ

{
  "title": "Judul Postingan Forum",
  "summary": "Ringkasan singkat postingan forum",
  "content": "Isi lengkap dari postingan forum.",
  "tags": ["tag1", "tag2"],
  "category": "6897401324867c87afbca3cd"
}

### Get All Forum Posts (with optional query params)
GET https://tugasakhir-production-6c6c.up.railway.app/forum/posts
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ODhlNzczMzJmNmVlNmEyZTMwN2QwNSIsIm5hbWUiOiJuYW5kYSBuYWRsaXJpbiAyIiwiZW1haWwiOiJhbHVtbmkudXBkYXRlZEBleGFtcGxlLmNvbSIsInJvbGUiOiJhbHVtbmkiLCJpYXQiOjE3NTQ3NTQwMDgsImV4cCI6MTc1NDc1NTgwOH0.scPBneI42pQonxu4bO2WOYegiWMckfBypAeFgvGkoLv6kpk0H_O5ZzYyG7hdKqg9AV8cKf_ptAyTrg2nCO5OWSnTQRVaO7qYPZnIbbHRGNIZW-jTL7Str5sUT90d9fLLb4nK7bKkDx5zXRx-DtC4VkycZVJgC2VYCG6aSQVNqhBqvoCBzy838AwSvE0EY_xfqKlFrMaPpqVUm8ic5J_LrhlEy8nXWvwKakb3vFj_xFfqL5hobElAW9d6juiY6CbzovvER1Gh4zATceGG7Ltiza00_vmFwCo_3xICCG0kqVupwr2lbNGFVV2MV-B-MdVyvgWWlBYAzWLzpgK0R8gGPw

### Get Single Forum Post by ID
GET https://tugasakhir-production-6c6c.up.railway.app/forum-posts/<forum_post_id>

### Update Forum Post by ID
PUT https://tugasakhir-production-6c6c.up.railway.app/forum/posts/68974a10f20510c8ed107a7c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ODhlNzczMzJmNmVlNmEyZTMwN2QwNSIsIm5hbWUiOiJuYW5kYSBuYWRsaXJpbiAyIiwiZW1haWwiOiJhbHVtbmkudXBkYXRlZEBleGFtcGxlLmNvbSIsInJvbGUiOiJhbHVtbmkiLCJpYXQiOjE3NTQ3Njc2OTYsImV4cCI6MTc1NDc2OTQ5Nn0.NMN0kWet4JLJGtrSBRUftbN6WM2QVYm_bRc7UpcBr6ajH4oztrYVHP4tO6OpHhobcoJULKEeAfpfOSHgLnPbHpk6MH9kscUNBD51jKDoSTL5jBW0turxm_VSe5AzAfryABtbwc_okOWPjm5HzeDGzGQPBN2Zt5OhZ1XiNhNNZFIXc7Mx5xwqFVyjd4faANa8-GmGstUfgW2Zm9bqq7wjEqC2Xo0-x_7KP6EYEHpyAL5iVPwtE0VXr1zEp4A2FllrhfAHnj-penwa3jGrsdXuy_pX44RknSZeeoQwTV9y-nCIUtvOIZHpcMSi9JyiahYON4HQJKvKXNiEDasM8GMWAA

{
  "title": "Judul Postingan Forum (update)",
  "summary": "Ringkasan update",
  "content": "Isi update",
  "tags": ["tag1", "tag3"],
  "category": "6897401324867c87afbca3cd",
  "pinned": true,
  "highlighted": false
}

### Delete Forum Post by ID
DELETE https://tugasakhir-production-6c6c.up.railway.app/forum/posts/<forum_post_id>
Authorization: Bearer 

### Like Forum Post
### Like Forum Post
POST https://tugasakhir-production-6c6c.up.railway.app/forum/posts/68974a10f20510c8ed107a7c/like
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ODhlNzczMzJmNmVlNmEyZTMwN2QwNSIsIm5hbWUiOiJuYW5kYSBuYWRsaXJpbiAyIiwiZW1haWwiOiJhbHVtbmkudXBkYXRlZEBleGFtcGxlLmNvbSIsInJvbGUiOiJhbHVtbmkiLCJpYXQiOjE3NTQ3NjI5NzUsImV4cCI6MTc1NDc2NDc3NX0.StdxWqT9MruiEqPdBYBkObEQoIAuHkJcAMBo_JhU9CIimzMFtbfRGgUHGyG1IQcfdr0aX0gJ5fKa6KU-SgWWyaHGVt7vUR4dRrInNsQOtVNtdP-QRcadALI8AI3vTP-te8i4jRUIi8SJhu9hO8uZzGWzCaap3AcjahPiMxhqFA2XbDRgWTr9agIOprJBRekvni1lpt_t8gzD0r7DmxKerBAh_HGFeCsU4W-98El1Pd5_MkqDgST2gxx5C9lde2NmFt1BKcIltY64iFhQzZfbK2Rg9tX3Pk_leTexmRE-JVQY0xegg_gDJbcyPYVjIntVy6OlH9PZxMEWbOcHIuX-KQ

### Unlike Forum Post
POST https://tugasakhir-production-6c6c.up.railway.app/forum/posts/68974a10f20510c8ed107a7c/unlike
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ODhlNzczMzJmNmVlNmEyZTMwN2QwNSIsIm5hbWUiOiJuYW5kYSBuYWRsaXJpbiAyIiwiZW1haWwiOiJhbHVtbmkudXBkYXRlZEBleGFtcGxlLmNvbSIsInJvbGUiOiJhbHVtbmkiLCJpYXQiOjE3NTQ3NjI5NzUsImV4cCI6MTc1NDc2NDc3NX0.StdxWqT9MruiEqPdBYBkObEQoIAuHkJcAMBo_JhU9CIimzMFtbfRGgUHGyG1IQcfdr0aX0gJ5fKa6KU-SgWWyaHGVt7vUR4dRrInNsQOtVNtdP-QRcadALI8AI3vTP-te8i4jRUIi8SJhu9hO8uZzGWzCaap3AcjahPiMxhqFA2XbDRgWTr9agIOprJBRekvni1lpt_t8gzD0r7DmxKerBAh_HGFeCsU4W-98El1Pd5_MkqDgST2gxx5C9lde2NmFt1BKcIltY64iFhQzZfbK2Rg9tX3Pk_leTexmRE-JVQY0xegg_gDJbcyPYVjIntVy6OlH9PZxMEWbOcHIuX-KQ

###
POST https://tugasakhir-production-6c6c.up.railway.app/forum/posts/68974a10f20510c8ed107a7c/pin
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4OTQwZGRhZmJmYTUxZjVkOTI3ODM3MCIsInVzZXJuYW1lIjoiYWRtaW4yIiwiZW1haWwiOiJhZG1pbjFAZXhhbXBsZS5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTQ3Njk1MzEsImV4cCI6MTc1NDc3MTMzMX0.UYnYWn9P8K1b1JLEooun3YXM0WBZYSK8XnDUCwr7WgTnEkUqx-0euC7BgSl4EcZJYjErESN9sNMvfGXRSEuPZ2zc0uEP8pWOuCp077PPZzhlrrFVS6qIjDsg4rDwuIVgw2j3KzaOGG0Kfze6iMiLyNQzHbtLkioqmTe9OfJMO2FogM126kHL6XIz734qaXuwJ8hEX82P0JCSIn0jTumOdo8r7qulEsWCIzQ8WDAXjqBcKzjWvXO11xMHObPUq6QGA5SoD_rd-sX23uoyOEWLitVDMWVZuI7lXtPoyK9OPfCJJLHS3tl3_Dxzs9j22XaoNCKSKdw9nqnU7y-V8eMfCg

### Unpin Forum Post
POST https://tugasakhir-production-6c6c.up.railway.app/forum/posts/68974a10f20510c8ed107a7c/unpin
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4OTQwZGRhZmJmYTUxZjVkOTI3ODM3MCIsInVzZXJuYW1lIjoiYWRtaW4yIiwiZW1haWwiOiJhZG1pbjFAZXhhbXBsZS5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTQ3Njk1MzEsImV4cCI6MTc1NDc3MTMzMX0.UYnYWn9P8K1b1JLEooun3YXM0WBZYSK8XnDUCwr7WgTnEkUqx-0euC7BgSl4EcZJYjErESN9sNMvfGXRSEuPZ2zc0uEP8pWOuCp077PPZzhlrrFVS6qIjDsg4rDwuIVgw2j3KzaOGG0Kfze6iMiLyNQzHbtLkioqmTe9OfJMO2FogM126kHL6XIz734qaXuwJ8hEX82P0JCSIn0jTumOdo8r7qulEsWCIzQ8WDAXjqBcKzjWvXO11xMHObPUq6QGA5SoD_rd-sX23uoyOEWLitVDMWVZuI7lXtPoyK9OPfCJJLHS3tl3_Dxzs9j22XaoNCKSKdw9nqnU7y-V8eMfCg

### Highlight Forum Post
POST https://tugasakhir-production-6c6c.up.railway.app/forum/posts/68974a10f20510c8ed107a7c/highlight
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ODU2YWQzYzYyNDNhOGJhZTVkMzNmZCIsIm5hbWFfcGVydXNhaGFhbiI6IlBUIE1hanUgSmF5YSAyIiwiZW1haWxfcGVydXNhaGFhbiI6ImhyZEBtYWp1amF5YXVwZGF0ZS5jb20iLCJyb2xlIjoicGVydXNhaGFhbiIsImlhdCI6MTc1NDc2OTg1MiwiZXhwIjoxNzU0NzcxNjUyfQ.exCwZi-A2Zcih5pzQYiiQlTjCOe1dz6BSuBveeCAbXuc1l7fm80gU_wjDGmaZhh9KaLGso2Kx-yyoytQJx2MQYGWG4o6TAoDfr7F3aposTdtYQ7wR72QKNif0hA4kSD1bFgL2JoZrg016P3HsquUZG59HqzGOW1bY9Dl35q2PYnGV_OPHJEXyodovRG1CP-JfN3pXUUK09e4rjEvFJfWooPWK9L4F5eSJmqY_yi85HEpivfKE9HqzHNgM3YMjo9LnuLXpfRFVAgZydU1iIbjK2P05Ndhs_BGf-Ai6VGhi9IsWzcL5mjEzwu3c_uD806ITR0edJZSYch11TE-SujQYg

### Unhighlight Forum Post
POST https://tugasakhir-production-6c6c.up.railway.app/forum/posts/68974a10f20510c8ed107a7c/unhighlight
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4OTQwZGRhZmJmYTUxZjVkOTI3ODM3MCIsInVzZXJuYW1lIjoiYWRtaW4yIiwiZW1haWwiOiJhZG1pbjFAZXhhbXBsZS5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTQ3Njk1MzEsImV4cCI6MTc1NDc3MTMzMX0.UYnYWn9P8K1b1JLEooun3YXM0WBZYSK8XnDUCwr7WgTnEkUqx-0euC7BgSl4EcZJYjErESN9sNMvfGXRSEuPZ2zc0uEP8pWOuCp077PPZzhlrrFVS6qIjDsg4rDwuIVgw2j3KzaOGG0Kfze6iMiLyNQzHbtLkioqmTe9OfJMO2FogM126kHL6XIz734qaXuwJ8hEX82P0JCSIn0jTumOdo8r7qulEsWCIzQ8WDAXjqBcKzjWvXO11xMHObPUq6QGA5SoD_rd-sX23uoyOEWLitVDMWVZuI7lXtPoyK9OPfCJJLHS3tl3_Dxzs9j22XaoNCKSKdw9nqnU7y-V8eMfCg

### Save Forum Post
POST https://tugasakhir-production-6c6c.up.railway.app/forum/posts/68974a10f20510c8ed107a7c/save
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ODU2YWQzYzYyNDNhOGJhZTVkMzNmZCIsIm5hbWFfcGVydXNhaGFhbiI6IlBUIE1hanUgSmF5YSAyIiwiZW1haWxfcGVydXNhaGFhbiI6ImhyZEBtYWp1amF5YXVwZGF0ZS5jb20iLCJyb2xlIjoicGVydXNhaGFhbiIsImlhdCI6MTc1NDc3NDQ5NywiZXhwIjoxNzU0Nzc2Mjk3fQ.ghkLAuPWUWtiPuo2s5uw-qeMbvVE0E6mJpyB64BDtW_Htu5-fV9QJHLc6TbmqnIp4KT3SRIrXINhY2w2W6WHzmG_Xm-qtbZpeeZwd4rm6cq7NoC82Ge0DaVoyHq5SeB2dOIqbpOVcRB3v3hjMg9Y5dYyS8vx4bLCn-YzWxcpA3xgBTTFWwNiqPS6Y8ahxcj5nI3ZKpSV7ztUyMM2DFR0voDvIcCyTJSjiM3XLkX7rlSgy8e6BRQ2ZackhIosAfpN0cQj-Pic5WWZCE83oBoQUr9GhPEhNZ4VpyMZv2rncWDUkMLG7SDhXE2XsYv9ER_7gsnG8BMjAu2wZ8GmxR-reQ

### Unsave Forum Post
POST https://tugasakhir-production-6c6c.up.railway.app/forum/posts/68974a10f20510c8ed107a7c/unsave
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ODU2YWQzYzYyNDNhOGJhZTVkMzNmZCIsIm5hbWFfcGVydXNhaGFhbiI6IlBUIE1hanUgSmF5YSAyIiwiZW1haWxfcGVydXNhaGFhbiI6ImhyZEBtYWp1amF5YXVwZGF0ZS5jb20iLCJyb2xlIjoicGVydXNhaGFhbiIsImlhdCI6MTc1NDc3NDQ5NywiZXhwIjoxNzU0Nzc2Mjk3fQ.ghkLAuPWUWtiPuo2s5uw-qeMbvVE0E6mJpyB64BDtW_Htu5-fV9QJHLc6TbmqnIp4KT3SRIrXINhY2w2W6WHzmG_Xm-qtbZpeeZwd4rm6cq7NoC82Ge0DaVoyHq5SeB2dOIqbpOVcRB3v3hjMg9Y5dYyS8vx4bLCn-YzWxcpA3xgBTTFWwNiqPS6Y8ahxcj5nI3ZKpSV7ztUyMM2DFR0voDvIcCyTJSjiM3XLkX7rlSgy8e6BRQ2ZackhIosAfpN0cQj-Pic5WWZCE83oBoQUr9GhPEhNZ4VpyMZv2rncWDUkMLG7SDhXE2XsYv9ER_7gsnG8BMjAu2wZ8GmxR-reQ


