### Get all alumni (hanya admin, dengan authorization)
GET https://tugasakhir-production-6c6c.up.railway.app/admin/alumni
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NWMyYTRhNzM5MzMxODhiMGM3MmQyMSIsInVzZXJuYW1lIjoiYWRtaW4xIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUzNDQ4NDY1LCJleHAiOjE3NTM0NTAyNjV9.gtqsAjYruWzbT9WYohFV5yyjeSPxygH4IZLVpgzCvvuYoSUtv3gkgwGmxtG44dDSU0uef8UsUJuII18UimreYB4KX3bx2G5op6-Gq8R1rOzenk52LWwwQOiOangh3KLhH4u0eWdhtnS8UDvSCl-y_JllblbPUjoA9ZM51GCB8f3clFipRyfaMuuFM2x4snRv8cbFLw5aZdeZEDVklFgaoAl9wcBS2DdFTjonjVv4X_bq0_7_snGPiE0qkHsS6PiY9aAeRwPjWNsJ0beUk44DgB8HbwXH1yrpBoXG6q5Sx7cRScZJIHstjNU2QmnxMLdyEHhLp8lqWPI1HNOnXbWYEg

### Get all perusahaan (hanya admin, dengan authorization)
GET https://tugasakhir-production-6c6c.up.railway.app/admin/perusahaan
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NWMyYTRhNzM5MzMxODhiMGM3MmQyMSIsInVzZXJuYW1lIjoiYWRtaW4xIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUzNDU0MzgxLCJleHAiOjE3NTM0NTYxODF9.fxlpNywU9r5lhdGzrtI_jqI5GNHQIRCourW0OixtrqTYWvXAfrwIjTFXyuic48ty2V21zQxRRga98idb4AlBBfj_0qsu7kPp8iHtB2_ndKf2XN796UHw098YcmhbPeF1X2X2-I1xAJ15PD1M3DbkO5a7BcTPudvF-wDGrVoFiStXxG5AoGYi4hMDqBaruaxYLJHtITGd8gaR3wR-ufupkek7qItde_mRryVWgNrADMKvr8Zmxk0qJAM2O8kOT7JEVF0cTVgd_qKRPdVYZ60mxK_a7fDkA4W8qfCtc5o2Lk58omH8nTnhhMXzRPK-m5NekKfJ4aQwe_82LAmEgY1Zzw


### Update data alumni by admin (PATCH /admin/alumni/:id)
PATCH https://tugasakhir-production-6c6c.up.railway.app/admin/alumni/685c266d3c044b2bf8775cae
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NWMyYTRhNzM5MzMxODhiMGM3MmQyMSIsInVzZXJuYW1lIjoiYWRtaW4xIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUzNDQ4Nzc4LCJleHAiOjE3NTM0NTA1Nzh9.am0tFpzglj9CZhi9C9dmj04ulsXw0elsvMfqJ0Z__PlbmDZOO3_wb0dPaKC63NOZAlQ2qzKo26U-BlIumxUu8WDK2OULqQFyVkuY-rUbs7ou0qDjm3eqCDXsQJOrdtRYTt3bwo0Obe7j9vlYDLUZDiAEKY136vHXjii62HNLteEEX-pmiENFmbTTP5nwJ2G2qqxnkFma19vTKlh17vLdFWWaKnHez_NNiMcfc_RvwzMAXN6maQ03FT3efY3zB0qORasAINPDyj96gdy7i7r0d394Z3cpn-KHjA9GjKdep3nEPyHqr5nXTIUm2p04iY1uKsTR1Qlf3I-VDtQOTWzugg

{
    "name": "Nama Alumni Baru",
    "nim": "987654321",
    "nohp": "08123456789",
    "alamat": "Jl. Baru No. 2",
    "program_studi": "Sistem Informasi",
    "tahun_lulus": 2023,
    "tanggal_lahir": "2000-01-01",
    "email": "alumni.baru@example.com",
    "password": "passwordbaru",
    "confPassword": "passwordbaru"
}

### Update data perusahaan by admin (PATCH /perusahaan/:id)
PATCH https://tugasakhir-production-6c6c.up.railway.app/admin/perusahaan/68826400e44ff373ff49a9d1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NWMyYTRhNzM5MzMxODhiMGM3MmQyMSIsInVzZXJuYW1lIjoiYWRtaW4xIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUzNDU0MzgxLCJleHAiOjE3NTM0NTYxODF9.fxlpNywU9r5lhdGzrtI_jqI5GNHQIRCourW0OixtrqTYWvXAfrwIjTFXyuic48ty2V21zQxRRga98idb4AlBBfj_0qsu7kPp8iHtB2_ndKf2XN796UHw098YcmhbPeF1X2X2-I1xAJ15PD1M3DbkO5a7BcTPudvF-wDGrVoFiStXxG5AoGYi4hMDqBaruaxYLJHtITGd8gaR3wR-ufupkek7qItde_mRryVWgNrADMKvr8Zmxk0qJAM2O8kOT7JEVF0cTVgd_qKRPdVYZ60mxK_a7fDkA4W8qfCtc5o2Lk58omH8nTnhhMXzRPK-m5NekKfJ4aQwe_82LAmEgY1Zzw

{
    "nama_perusahaan": "PT Maju Jaya Baru",
    "email_perusahaan": "majujaya.baru@example.com",
    "alamat": "Jl. Industri No. 10",
    "bidang_perusahaan": "Teknologi",
    "nomor_telp": "02112345678",
    "npwp": "123456789012345",
    "deskripsi_perusahaan": "Perusahaan teknologi terdepan.",
    "password": "passwordbaru",
    "confPassword": "passwordbaru"
}

### Get pelamar dengan status diterima/ditolak (khusus perusahaan, dengan authorization)
GET https://tugasakhir-production-6c6c.up.railway.app/pelamar/diterima-ditolak
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ODNhYTc1Y2NkOWVkMmJmZGYxNDBiNiIsIm5hbWFfcGVydXNhaGFhbiI6IlBUIE1hanUgSmF5YSAyIiwiZW1haWxfcGVydXNhaGFhbiI6ImhyZEBtYWp1amF5YXVwZGF0ZS5jb20iLCJyb2xlIjoicGVydXNhaGFhbiIsImlhdCI6MTc1MzU1NjE5NCwiZXhwIjoxNzUzNTU3OTk0fQ.rjPVIp2oevWPKiNROFG-_QI9G9fboGjlsFy0U6VSwCMsHhPJ4HwUgHbt1qUqiDeF87bGmvqMm3FORkH0aEtBGY1-BOM0_YkvrfiuYtqMzeiNpcwXUM08T4BTbSwU-vkiynaqf4rOSLtZht5X3gY6iX32sb5t16Dq1bZug8yzl18BOpR8tSZ0naWyAtv-CrsnCk89KtI0S2dTxdO-VH446ZzMC-Vti6EZIEq0KHWyfV1M2STyTshAA6WY9_3PEnRwoOVb4EPAFOs36NqFU0NDWdN9KXNziPWxeplSRnJW-Vxv2fkJp7vYE2Mq-Cof3yCWkIhMN2SBEG4o8W-X9pM-zw


### Get semua alumni yang pernah melamar ke lowongan perusahaan ini (khusus perusahaan, dengan authorization)
GET https://tugasakhir-production-6c6c.up.railway.app/perusahaan/alumni-pelamar
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ODU2YWQzYzYyNDNhOGJhZTVkMzNmZCIsIm5hbWFfcGVydXNhaGFhbiI6IlBUIE1hanUgSmF5YSAyIiwiZW1haWxfcGVydXNhaGFhbiI6ImhyZEBtYWp1amF5YXVwZGF0ZS5jb20iLCJyb2xlIjoicGVydXNhaGFhbiIsImlhdCI6MTc1NDUxMDEyNCwiZXhwIjoxNzU0NTExOTI0fQ.riAOtKzgEF13Qwv5NlHbnfEm_254suxnlk9yk3Q7zUQ4d-S7ssfQaq2awOx_UbWC1HQbZidYo_AN_4Nl7x5GAThpbdJp-Qh-fvfLfU2E4MABL0LGJ__7dVHCN1LrBnq26l6sFHyqBbbak9hWeqHKfTEcV7WOu6pFvFYAS5vabnNi6u1_kPie2BOZVXi39FqKBo1fc0wr9MpPmrCvj0222wsTaKXJE779AvIUPCyQHUYfmpwVKbQryPCoX-Ckd8RbGNKUTcORI-r6PicEDVbmVbPge4DYz1kW_X8HYBu5NQdOpJ20GoHLaIZMfUGlWtQqTc_FxG0-qfI3lXVRQ06SAw

### Get daftar semua lamaran alumni yang sedang login (hanya alumni, dengan authorization)
GET http://localhost:5000/pelamar/alumni/me
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4OWFlMTU1ZGYyODNiN2JlMDkyY2RiNiIsIm5hbWUiOiJuYW5kYSIsImVtYWlsIjoiYWx1bW5pLnVwZGF0ZWRAZXhhbXBsZS5jb20iLCJyb2xlIjoiYWx1bW5pIiwiaWF0IjoxNzU1MTg4MzY3LCJleHAiOjE3NTUxOTAxNjd9.tERpBcUjhEtLZEyrzJz8VSBMKltafFVIG-t-eRs8A2yjoLLFXhwkEJlPLdXguoI2G0BFnpkWu2mIyh4eYwBl9orGTyE7AZbSeKINySjc7KRDkiHGoCbdHTGy4z0LyV-yJmjaF-IMAapBZim1mWSjYPE9TJ7PWsU21i4_BPCXUqowQyk4trTe--HcogCWxmRmKfpNRxXwQfwj49HQJOEgqafo28uSHlNOzeaqj9-oKFRPyJPFiJudpJiuVWGl5Pppnf3uokuhpsH86Q9RG3FAzcq0JxDSsxGLw5Sxf964pGZohtPe_Pmlbo-pVEdU5wnTSORZbE7N6E9daEWFT7uvjA

