### Login Alumni
POST https://tugasakhir-production-6c6c.up.railway.app/login
Content-Type: application/json

{
    "email": "alumni.updated@example.com",
    "password": "123456"
}

### Login Perusahaan
POST https://tugasakhir-production-6c6c.up.railway.app/login
Content-Type: application/json

{
    "email": "hrd@majujaya.com",
    "password": "123456"
}

### Login Admin
POST https://tugasakhir-production-6c6c.up.railway.app/login
Content-Type: application/json

{
    "email": "adminbaru1@example.com",
    "password": "adminpassword123"
}

### Login SuperAdmin
POST https://tugasakhir-production-6c6c.up.railway.app/login
Content-Type: application/json

{
    "email": "superadmin1@example.com",
    "password": "supersecurepassword456"
}


### Get Alumni 
GET https://tugasakhir-production-6c6c.up.railway.app/alumni/me
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ODhlNzczMzJmNmVlNmEyZTMwN2QwNSIsIm5hbWUiOiJuYW5kYSBuYWRsaXJpbiAyIiwiZW1haWwiOiJhbHVtbmkudXBkYXRlZEBleGFtcGxlLmNvbSIsInJvbGUiOiJhbHVtbmkiLCJpYXQiOjE3NTQ0MTU1MzksImV4cCI6MTc1NDQxNzMzOX0.mZP-Jx0CUG9UH0nBE4hgqIwNS_uYE69twqP98GiXeMqpcER6Ibm2DXQ3JO347S3FcF45-RK7sCWYc0STT1wm-19gdaWMP5UvV7vRmQnK-lcvepVYFN4AoAed1Mdggk3y2noowwW756Rek2Nm4a7bdtc2FQeDMYJCVU7KneBhXsLCbziMc__z5VaUKrt2sFHzkuVqXM6Hckk6nNZ7j9OaUf12AeUBa1ynwMITS2FVQ553zeNpUhzQQhSBwKP4wJ_BQXIQ1PlmDlUd1dBvRuLl2FzRalXdLg602xh6RTtYopL3niKd9uVI9aRRnG48SZQNYdD8YN7FrYA2T56cVa_3wA


### Get Perusahaan
GET https://tugasakhir-production-6c6c.up.railway.app/perusahaan/me
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4OWEzMjQyZjY3NjZhZWY3MDZkZWQwZSIsIm5hbWFfcGVydXNhaGFhbiI6IlBUIE1hanUgSmF5YSAyIiwiZW1haWxfcGVydXNhaGFhbiI6ImhyZEBtYWp1amF5YS5jb20iLCJyb2xlIjoicGVydXNhaGFhbiIsImlhdCI6MTc1NTM5NTYzMiwiZXhwIjoxNzU1Mzk3NDMyfQ.F9dQ2O0tcc9k5m8cndN8UxWGo18H_j1XOB8ybJS-HuL-tTYxL_q215LmypVFckAU-7lIvRw7Bbo7_ZAKlBuyx0zA_U7CIqrmVbDuGg3O8iP4cnH9kuiDtZiKURi4oQnanlddxJE-Bap7fRGGqF5bQ7vn1eHZ4FhHcdVkMavDhn4nNv4SJvBRiVT9MdXky7-jNbjYYPL09ndnhH9IzlXf9pm6naeWyXZmRpsswgvGP7fZjwZH8ZHk5vt3lEv9uH_IzLfJpVb9CkDCUAsg2saVWx4K3exG32GhKpiUH5Gxjj3HrfSPE2KUqU69VW3FDDeKJus93h_kGBl0QzMQNZlMZQ

### Get Admin
GET https://tugasakhir-production-6c6c.up.railway.app/admin/me
Authorization: Bearer <your_admin_jwt_token_here>

### Protected Endpoint (cek token valid)
GET https://tugasakhir-production-6c6c.up.railway.app/protected
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4OWE0ZDlhMDgwNTFlOWI0NDNmNDM1YyIsIm5hbWFfcGVydXNhaGFhbiI6IkNWIE1BSlUgSkFZQSAyMyIsImVtYWlsX3BlcnVzYWhhYW4iOiJpbmZvMjFAc3Vrc2Vzc2VsYWx1LmNvbSIsInJvbGUiOiJwZXJ1c2FoYWFuIiwiaWF0IjoxNzU1MDA2MzQ2LCJleHAiOjE3NTUwMDgxNDZ9.a8BahP9ho11uYCy3F60itIjN6U_ChmqyjXJUAWWfAVNcArUq-weok23EVo8ScxSn970GAccdmhbyBoCNG4kEwSy0yeZzde_4-AOwt1-sUPUlPQ2xgKUHIIMTfxfvx4abstWhzqRVKUhUEj0D7bcFi_-eVmNdj1acRBroQOApONrgloBITTRlIvUzvOUiLeiLbM0xqBKtLGfiwdpHIU2FXeeszaba8Qol4th83G67fSmr7b0DHoJe83IUlUeXY5vT3w5zguDduu470lC9DMqB9pOs-W0ySFNEVV3ZdWZfVCJEUhmklWyKwbKz4IJ3rz7x-j3r2fJFZ7iE8LaSJsF5og



