### Logout (semua tipe user)
POST https://tugasakhir-production-6c6c.up.railway.app/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NWVkODlhNjhiN2RlMzk1ZWFjYjBkOCIsIm5hbWFfcGVydXNhaGFhbiI6IlBUIE1hanUgSmF5YSAyIiwiZW1haWxfcGVydXNhaGFhbiI6ImhyZEBtYWp1amF5YS5jb20iLCJyb2xlIjoicGVydXNhaGFhbiIsImlhdCI6MTc1MTIxNDUxNiwiZXhwIjoxNzUxMjE2MzE2fQ.V_VtptfIBHxV2m3dmRMGovuL14crZ_Q30kLX8v0L_RHo0Cz1KfLgZu93Gm_Y1vNiZ1h7JQ_8B_O-cwfEuci5v0GYJ_6BFbs0n9giXjNNUDBvte6dpHufEGXXiYaE5dlogcSGbmLgZCnddsC670HZNgvQNj_B1Zs5WznP-zgSHkcOvXy7_7l5lzWLZS-EtVronv98dxzSDMW9VDZB4DPFiOmbtYMezC_UHQe2IbtAkeAMIXMfIHxKIjA1TQwgBJCz3Ggf3IRyzEirAr8x2SifRIELZb53B6v82GUWcIN0eo9DRLfaleV4oHPC-MRfzDyY-GXQyF-jyTN7OYdfDfoxiQ
