### Melamar Lowongan (POST /pelamar)
POST https://tugasakhir-production-6c6c.up.railway.app/pelamar
Content-Type: application/json
Authorization: Bearer token

{
  "lowongan": "685ef2999420d08eac333b60"
}
### Melihat Daftar Pelamar pada Lowongan Tertentu (GET /lowongan/:id/pelamar)
GET https://tugasakhir-production-6c6c.up.railway.app/lowongan/6863b4cd6b66ff6e5140b3ed/pelamar
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NWVkODlhNjhiN2RlMzk1ZWFjYjBkOCIsIm5hbWFfcGVydXNhaGFhbiI6IlBUIE1hanUgSmF5YSAyIiwiZW1haWxfcGVydXNhaGFhbiI6ImhyZEBtYWp1amF5YS5jb20iLCJyb2xlIjoicGVydXNhaGFhbiIsImlhdCI6MTc1MTM3NTIxMSwiZXhwIjoxNzUxMzc3MDExfQ.tHsq3NSU3SYlE-JfsYo09VlY-BfO20DQMGGfi76_o89J1DXdgG8iDwB2yLqJGjT3WYulStGXfjgEpM8no3SxDUTjCfxAMxIXiLeT9fTal_eQ-Y2JscFq_q9yNQuNcW4kD05i2IHlsF5__r-e7DWdaEk3Cr-h4-ETs8ce8wbpNs0e7ESc6zdvaI48RPkhgxqt8ep4XqvPdJwk4ZERln2uiGGabnHT_zeNdgUmqG9kN7VbeSp6kpvTmvlOp-ZN63kArQ3I_-4kFDi5ht4JIF5UaJPeI4UZAwzqwNuSJAO2KmXdFLhQZ2BWgHLLcx8-1Hkqo2i-eG3oWEEfxTUCGIYkEA

### Menerima Pelamar pada Lowongan Tertentu (PATCH /lowongan/pelamar/:pelamarId/terima)
PATCH https://tugasakhir-production-6c6c.up.railway.app/lowongan/pelamar/685c266d3c044b2bf8775cae/terima
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NWVkODlhNjhiN2RlMzk1ZWFjYjBkOCIsIm5hbWFfcGVydXNhaGFhbiI6IlBUIE1hanUgSmF5YSAyIiwiZW1haWxfcGVydXNhaGFhbiI6ImhyZEBtYWp1amF5YS5jb20iLCJyb2xlIjoicGVydXNhaGFhbiIsImlhdCI6MTc1MTM3NzU3NSwiZXhwIjoxNzUxMzc5Mzc1fQ.bsMhhC3EZHCrRTXnyxEvDgcCtaL9w7gyCKVe7c8EojNwRHNph77E-x3eTA4s4MJMaioHwjcBEt6KfY_N1KOl1DoDTRYP0tSR-_rhRPGfUlLHyW8CoRkulutDuwalzFIOPVuM1zS-VI-y0oOEj7qphZ2kf1ocbW6luFut17lXQ9WKN_39pgPM75bOyMGi98ZHre-AiFpdF39FyMFUdQ8cmHvDbvQX06JdM6vvtWzn0EVPlzRjrfhRyzlWP6KWVQj4r5YMP1CQfUP-keq9CQ_JDQ_p77-sGflLUXKj1Dr57AjtuGtMEja6p1ovdWiSm_XBeTrjmekab09mAK9lY3Zp8A

{
"pelamarId" : "685c266d3c044b2bf8775cae",
"lowonganId": "6863b4cd6b66ff6e5140b3ed"

}

### Hitung Jumlah Pelamar di Semua Lowongan Milik Perusahaan (GET /lowongan/pelamar/count)
GET https://tugasakhir-production-6c6c.up.railway.app/lowongan/pelamar/count
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ODU2YWQzYzYyNDNhOGJhZTVkMzNmZCIsIm5hbWFfcGVydXNhaGFhbiI6IlBUIE1hanUgSmF5YSAyIiwiZW1haWxfcGVydXNhaGFhbiI6ImhyZEBtYWp1amF5YXVwZGF0ZS5jb20iLCJyb2xlIjoicGVydXNhaGFhbiIsImlhdCI6MTc1NDM0MTc3NSwiZXhwIjoxNzU0MzQzNTc1fQ.kyU12M8sPP4niwiPmnlQaeeZ29uZ21qMmSTR7rsVhCaGDRuhrMxALyy5ajLRZmXtynDy5xy7va-h6VqdufTw6Cr2n5QN5ml4FNxYA6je0DgAj5sJ6ED2EHVrtOnVllt3xaEqk1Nwg29RclaobZ5fipX8b8ApJUIR0xtVJecygPUYCJqDfJsHde3xn5fyxfAgN-aQmVa9YdHL-ABbCnNZrbusCsk21GEuX4epxT1Lu9fh98LNgbOpLXkDVtGX6QzG7tTfE5kJ3e3OACDmnKl-RnY3EiwkDQVQC1w8NMJcstfvrEjpeYEHgdrkNmFo2uCZ_5X4PY7gt-gOveWPD8ajTw


### Hitung Jumlah Pelamar Diterima/Ditolak di Semua Lowongan Milik Perusahaan (GET /pelamar/count/diterima-ditolak)
GET https://tugasakhir-production-6c6c.up.railway.app/pelamar/count/diterima-ditolak
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ODU2YWQzYzYyNDNhOGJhZTVkMzNmZCIsIm5hbWFfcGVydXNhaGFhbiI6IlBUIE1hanUgSmF5YSAyIiwiZW1haWxfcGVydXNhaGFhbiI6ImhyZEBtYWp1amF5YXVwZGF0ZS5jb20iLCJyb2xlIjoicGVydXNhaGFhbiIsImlhdCI6MTc1NDM1MTIwOCwiZXhwIjoxNzU0MzUzMDA4fQ.XlRq4fclBpAv8DyDH1VKrrKFfw-TwidWK0DRkvBgy3D2nidJ4Km2S9BNxKTuoP5IsElQ4jKVPE6PqkiTSL83D3edxoPzaip-qNUdGKoR8Fh7j04mXHWBSIP0TG_UiajlOjV91wsfep0Pss8SfhDRQVJecLxnhDezkAlmctmY32wuAiTCppu7a_chNcnTGMmInLLmo0A2fT_gsJ2zRkpB7oR0h-tc29Pk9RSVXKq8hcsMTH6BKM_Dp5JkyO5JlwQBV5cT1SgL3HCUTvyimNvNiZzmim5wAwgtLmk8RGjbRfTiKBm6WATDA3WAm7YhjNkkslWHsUojTQGMcKs90et2xA

### Grafik Jumlah Pelamar per Bulan per Tahun (GET /pelamar/grafik/per-bulan-tahun)
GET https://tugasakhir-production-6c6c.up.railway.app/pelamar/grafik/per-bulan-tahun
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ODU2YWQzYzYyNDNhOGJhZTVkMzNmZCIsIm5hbWFfcGVydXNhaGFhbiI6IlBUIE1hanUgSmF5YSAyIiwiZW1haWxfcGVydXNhaGFhbiI6ImhyZEBtYWp1amF5YXVwZGF0ZS5jb20iLCJyb2xlIjoicGVydXNhaGFhbiIsImlhdCI6MTc1NDM1MzM4MCwiZXhwIjoxNzU0MzU1MTgwfQ.FNbI9HzMyRI5LJDpm4FlgH2-5BzVFQAC01nKOARKbNUuQ5Zvj7_4-61alM-iJ1P_QH0WJNKgcIlR6EnWykzeqiTrj9sRF_j75QYD-h2vn5YAYhk3mhBz-F5GLvmnA7FXpPOOCn6QvfkQUmVB-il2__ef1rLnZQQ7xQJhKXuA7CfBLO5L1CJ1-jDTShh6YgpHM-8Flcvm32LZhQo8Z5ir3g7C0fNi2MiYwLaf_EfS-DA12u5lURYrhAPRUPlQhXBfOrgBFYT1tCQQChnrFjiQ6jqV-oszvGG6HWBtxtkfhiLwKLNiiP1fOy7uCM_BHPJSoFH1gIgLc5TiYC_Ka2aR2g

### Statistik Lamaran Alumni (GET /pelamar/statistik/alumni)
GET https://tugasakhir-production-6c6c.up.railway.app/pelamar/statistik/alumni
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ODhlNzczMzJmNmVlNmEyZTMwN2QwNSIsIm5hbWUiOiJuYW5kYSBuYWRsaXJpbiAyIiwiZW1haWwiOiJhbHVtbmkudXBkYXRlZEBleGFtcGxlLmNvbSIsInJvbGUiOiJhbHVtbmkiLCJpYXQiOjE3NTQ0Nzk0NzIsImV4cCI6MTc1NDQ4MTI3Mn0.WtLAEm-QpVMV5piO5VBSiqI5AyBSZYfOS5YhT_EZxs_RMaoTnuAr7EiYBERLZJaCbHu8NIyXKAi3lRdBDemsnlnB9U09Y4-D5ikv1MiNDbDnyUtxA0A2gmE-R2KpUvdhzN-ON5rpKOjoq0Iv_zL-nt8y7WUlt5F6nNE7VUwWVJsMNSQEqY6TBb6WoGLsm9YSf2OOVYxC6HdWs6aSqDSBWnbYOnoRpLhzVTVgguS5IXxw48PJxY7D3CTz8iUw_uduu_3j8MS7EZZ9h2cs4-a2uUYaqkPeDIWVtrAsMNVNrdeGtsaTFrmoSa_v2je-DgnDZEYspIGR2RTXcuvByE0C-Q

### Rekomendasi Lowongan untuk Alumni (POST /pelamar/rekomendasi-lowongan)
POST https://tugasakhir-production-6c6c.up.railway.app/pelamar/rekomendasi-lowongan
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ODhlNzczMzJmNmVlNmEyZTMwN2QwNSIsIm5hbWUiOiJuYW5kYSBuYWRsaXJpbiAyIiwiZW1haWwiOiJhbHVtbmkudXBkYXRlZEBleGFtcGxlLmNvbSIsInJvbGUiOiJhbHVtbmkiLCJpYXQiOjE3NTQ0ODMzMDIsImV4cCI6MTc1NDQ4NTEwMn0.pJjtwVCMQ8pqCLMSYFmePl8hesJjOe2iWEH2Q8NNnLTWQpVSeKaL8V56nHcVfKbVgFRC_9PouhNal8nbAm-twzw1tduWAgH4PdEUzbj7ACAPiUWwA4N9fsoe9Sf2FF-KXnUQaTU1mg7TFTGOeesCOvTbS1cUHqmU1tpwaJrGRDrbg0ZbYfrIxFdAnwyojZRAY7JzE2iK7dy3db9hQ5I0XeaIGw2v4a4c_gzeZD96Xf2Llpx08pd7Ox37EAimolW4ZioCjcdFm1bk75BNPTLhQu9_bX_3cgPDS7IAC5wgU09_m6L7f8P03RsdvXSpuOjx1R7RH6Zo0dtFenoyiTC8YA





