### Register Alumni
POST https://tugasakhir-production-6c6c.up.railway.app/alumni
Content-Type: application/json

{
    "name": "Siti Aminah",
    "email": "siti.aminah@example.com",
    "nim": "3202216125",
    "password": "abcdef",
    "confPassword": "abcdef"
}

### Register Perusahaan
POST https://tugasakhir-production-6c6c.up.railway.app/perusahaan
Content-Type: application/json

{
    "nama_perusahaan": "PT Sukses Selalu",
    "email_perusahaan": "info@suksesselalu.com",
    "password": "abcdef",
    "confPassword": "abcdef"
}

### Register Admin
POST https://tugasakhir-production-6c6c.up.railway.app/admin/register
Content-Type: application/json

{
    "username": "admin2",
    "email": "admin1@example.com",
    "password": "123456",
    "confPassword": "123456"
}
