### Search Alumni (Perusahaan, Admin, Alumni)
GET http://localhost:5000/perusahaan/alumni?q=nanda
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ODU2YWQzYzYyNDNhOGJhZTVkMzNmZCIsIm5hbWFfcGVydXNhaGFhbiI6IlBUIE1hanUgSmF5YSAyIiwiZW1haWxfcGVydXNhaGFhbiI6ImhyZEBtYWp1amF5YXVwZGF0ZS5jb20iLCJyb2xlIjoicGVydXNhaGFhbiIsImlhdCI6MTc1MzY1MjQ2NywiZXhwIjoxNzUzNjU0MjY3fQ.Sf3T3FK1nFI5YJOXlW5yEPiHSTaawR4GuGWCPLoEDigiBLj8X1cl1qyboEAMS6wGssYgoIr9ck3XivvFGX6my0DlG3F9NpnGsmaYmcN_YCdze-x1wIAevDhC0LZuLY0klR-wjTBXpzjNTFAJIcmF4_B39e96n4zSq7rR8wmD_7gJuuqHu0UY_lMCExcRINjvroIkCCrYRpYyyZ4aW_91ZLt9yq1gCytSN4nV0HDxqxiBeieBQEpG4x_3NODLbYZrsqGmKWqUS4nzY9ThA1MxC7B1DXLKT54E3MLnb4BHYPWQBrwU7lddG4X9-2LmVAPVhKvaLPt7LdR7M-SW49NhtQ
