### Register Super Admin
POST https://tugasakhir-production-6c6c.up.railway.app/superadmin/register-superadmin
Content-Type: application/json

{
  "username": "superadmin1",
  "password": "supersecurepassword456",
  "email": "superadmin1@example.com"
}

### Create Admin (by SuperAdmin)
POST https://tugasakhir-production-6c6c.up.railway.app/superadmin/create-admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4OWFlMGY3ZGYyODNiN2JlMDkyY2RhMyIsInVzZXJuYW1lIjoic3VwZXJhZG1pbjEiLCJlbWFpbCI6InN1cGVyYWRtaW4xQGV4YW1wbGUuY29tIiwicm9sZSI6InN1cGVyYWRtaW4iLCJpYXQiOjE3NTQ5ODA2MDQsImV4cCI6MTc1NDk4MjQwNH0.SjWSfdtSw6XNx82qF1yzBAyCIv2PMaVqlvHiNqYL0l2C7Lviq1l49hcHkqR65VP2gPOlL5vPJqv3JgkCG9PJMUrIZE9IEE6E1rUWWcD4me48XhUGJIfXI4fC8vzz_PR_7ZMIevwe4PmgoQAtTazllOr4j4zEGgHw8gZ34jGht3BkoDxrSNAjh0lPCNTTEEbF2-hRVENz8_RVcND4RH07BYPJiMpxyCzgH4lrFPg7x0GD6m1zwrIlyhhDkBpMFedmJO0zEJGaMje_CvRGRemoWwXMTUJQpQuSDyBeSYWnLIcTwD9VIwPoe0MQds6vm4ZwnYY_jnqh9P-5Kr6qGZZAug

{
  "username": "adminbaru1",
  "password": "adminpassword123",
  "email": "adminbaru1@example.com"
}

### Edit Admin (by SuperAdmin)
PUT https://tugasakhir-production-6c6c.up.railway.app/superadmin/edit-admin/68991844594db4e21b1f381d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4OTkxNmE2ZTc2ZTI5N2YyYjRjODY3ZCIsInVzZXJuYW1lIjoic3VwZXJhZG1pbjEiLCJlbWFpbCI6InN1cGVyYWRtaW4xQGV4YW1wbGUuY29tIiwicm9sZSI6InN1cGVyYWRtaW4iLCJpYXQiOjE3NTQ4NjM2NTUsImV4cCI6MTc1NDg2NTQ1NX0.xOifqB5zOadzg4LYPi3ZWhXFzfdXw1ok-RvGvxX1a3BczPdv_eexKXpc0EPzqkVFsaIN2WQn0nUbngmMLiiOBvdqmw5Tn8OCKAUKDRvpQtQyN3hWX50T9gzCmm7wEDQV-RIlVpIFS6wnyQEGndSk5Jvq1X60ULgxxbDpIituDY-okEnZz4hpwRUgp8CdsEfB2yLKT8jHkJLvbHinvy4xXtvAnGOvu4moZKAevPeNbSXDJU2GMW5UDtshuZA5WCU0AenYfH4P2YH-2LuV3827noQ8m5qxVQb_mUXHUg3jt46hExtE3AtK2I-1zrz5h9eax94RmJmjx_iZFOCFuOFglg

{
  "username": "adminbaru1_edited",
  "password": "newpassword456",
  "email": "adminbaru1_edited@example.com"
}

### Delete Admin (by SuperAdmin)
DELETE https://tugasakhir-production-6c6c.up.railway.app/superadmin/delete-admin/68991844594db4e21b1f381d
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4OTkxNmE2ZTc2ZTI5N2YyYjRjODY3ZCIsInVzZXJuYW1lIjoic3VwZXJhZG1pbjEiLCJlbWFpbCI6InN1cGVyYWRtaW4xQGV4YW1wbGUuY29tIiwicm9sZSI6InN1cGVyYWRtaW4iLCJpYXQiOjE3NTQ4NjM2NTUsImV4cCI6MTc1NDg2NTQ1NX0.xOifqB5zOadzg4LYPi3ZWhXFzfdXw1ok-RvGvxX1a3BczPdv_eexKXpc0EPzqkVFsaIN2WQn0nUbngmMLiiOBvdqmw5Tn8OCKAUKDRvpQtQyN3hWX50T9gzCmm7wEDQV-RIlVpIFS6wnyQEGndSk5Jvq1X60ULgxxbDpIituDY-okEnZz4hpwRUgp8CdsEfB2yLKT8jHkJLvbHinvy4xXtvAnGOvu4moZKAevPeNbSXDJU2GMW5UDtshuZA5WCU0AenYfH4P2YH-2LuV3827noQ8m5qxVQb_mUXHUg3jt46hExtE3AtK2I-1zrz5h9eax94RmJmjx_iZFOCFuOFglg

### Get SuperAdmin Me
GET https://tugasakhir-production-6c6c.up.railway.app/superadmin/me
Authorization: Bearer <your_superadmin_jwt_token_here>



