### Tambah NIM lewat input text
POST https://tugasakhir-production-6c6c.up.railway.app/tambah-alumni/tambah-nim
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4OWFlMTBkZGYyODNiN2JlMDkyY2RhYiIsInVzZXJuYW1lIjoiYWRtaW5iYXJ1MSIsImVtYWlsIjoiYWRtaW5iYXJ1MUBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1NDk4MDY1MCwiZXhwIjoxNzU0OTgyNDUwfQ.TnVMrqaL2l8HGWb0yIlf8kJeKwVb5T_Ph1FwX-NihCbjeHSvImIYgK2T4LGiVtPJ58Ssu_G0RTEbE9fRSZKe-JwHRwxPFWoaT-BtyPr8V-lHLRCGGnO9GJKMKs4Ud-qgIW9CBTI3bj4CdTLnhmc9orQRHC9I1CuGIXCi1bnQLXKL0EwdYed12cesUN4N4ovct_4UiW-BzaGeCVqa-32CEgxf8HHpTeM1c-TOjL75Jhc-5r5ePF0x7_lsw_H2FIFIWdCWj9-558sLw9WVt9dpdYVax2uB85CiV8gutq-vFE0LxJKID8ouvyCbuQnn1ZlUdmL9F6s9RbSX87wzrBb7KQ

{
  "nim": "3202216125"
}

### Tambah NIM lewat file XLS/XLSX
POST https://tugasakhir-production-6c6c.up.railway.app/tambah-alumni/tambah-nim-xls
Content-Type: multipart/form-data
Authorization: Bearer <your_token_here>

// Ganti path/to/your/file.xlsx dengan path file XLS/XLSX yang ingin diupload
file=@path/to/your/file.xlsx
